# This file is automatically generated by SnowBlower.
# Do not edit this file directly as your changes will be overwritten.
# Instead, modify your flake.nix configuration to update just commands.

# Display the list of recipes
default:
  @just --list

# using Gemini as base
ai-gem:
	aider --no-show-release-notes --model gemini --watch-files --no-suggest-shell-commands --no-detect-urls --git-commit-verify --lint-cmd treefmt

# using Sonet as base
ai-son:
	aider --no-show-release-notes --model sonnet --watch-files --no-suggest-shell-commands --no-detect-urls --git-commit-verify --read CONVENTIONS.MD --lint-cmd treefmt
