# This file is automatically generated by SnowBlower.
# Do not edit this file directly as your changes will be overwritten.
# Instead, modify your flake.nix configuration to update just commands.

[private]
[doc('Display the list of recipes')]
default:
  @just --list

[group('Aider')]
[doc('using Gemini as base')]
ai-gem:
		aider --no-show-release-notes --model gemini --watch-files --no-suggest-shell-commands --no-detect-urls --git-commit-verify --lint-cmd treefmt

[group('Aider')]
[doc('using Sonet as base')]
ai-son:
		aider --no-show-release-notes --model sonnet --watch-files --no-suggest-shell-commands --no-detect-urls --git-commit-verify --read CONVENTIONS.MD --lint-cmd treefmt

[group('Pre-commit')]
[doc('Run precommit on all files')]
pre-commit-all:
		pre-commit run --all-files
