# FROM docker.io/use-the-fork/snow-blower-devcontainer:latest
FROM localhost/use-the-fork/snow-blower-devcontainer:latest
# FROM ghcr.io/use-the-fork/snow-blower-devcontainer:latest


# cache /nix
VOLUME /nix