["formatter.alejandra-lint"]
command = "alejandra"
includes = ["*.nix"]
priority = 0

["formatter.deadnix-lint"]
command = "deadnix"
includes = ["*.nix"]
options = ["--edit"]
priority = 0

["formatter.keepsorted-format"]
command = "keep-sorted"
excludes = [".snowblower/*"]
includes = ["*"]
priority = 0

["formatter.shfmt-lint"]
command = "shfmt"
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-s", "-w"]
priority = 0

["formatter.statix-lint"]
command = "statix-fix"
includes = ["*.nix"]
priority = 0
